---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[securitymonkey::default]
    attributes:
      securitymonkey:
        log_level: DEBUG
        password_salt: 70c4e7da-5c42-4892-b23c-8000208e4732
        secret_key: da92bde9-cec0-40c0-ba6f-cbb81e812ab0
